openapi: 3.0.2
info:
  title: Reddit API
  version: TODO
  description: >-
    An OpenAPIv3 schema for Reddit's public API endpoints, automatically
    generated from Reddit's automatically generated API documentation.
  contact:
    url: 'https://github.com/danopia/various-openapi-schemas'
servers:
  - url: 'https://oauth.reddit.com'
    description: Accepts authenticated requests that contain a bearer token.
  - url: 'https://www.reddit.com'
    description: Accepts authentication flow (and anonymous) requests.
components:
  securitySchemes:
    redditOAuth:
      type: oauth2
      description: 'https://github.com/reddit-archive/reddit/wiki/OAuth2'
      flows:
        authorizationCode:
          authorizationUrl: 'https://www.reddit.com/api/v1/authorize'
          tokenUrl: 'https://www.reddit.com/api/v1/access_token'
          scopes: &ref_0
            creddits: Spend my reddit gold creddits on giving gold to other users.
            modnote: Access mod notes for subreddits I moderate.
            modcontributors: >-
              Add/remove users to approved user lists and ban/unban or
              mute/unmute users from subreddits I moderate.
            modmail: Access and manage modmail via mod.reddit.com.
            modconfig: >-
              Manage the configuration, sidebar, and CSS of subreddits I
              moderate.
            subscribe: >-
              Manage my subreddit subscriptions. Manage "friends" - users whose
              content I follow.
            structuredstyles: Edit structured styles for a subreddit I moderate.
            vote: Submit and change my votes on comments and submissions.
            wikiedit: Edit wiki pages on my behalf
            mysubreddits: >-
              Access the list of subreddits I moderate, contribute to, and
              subscribe to.
            submit: Submit links and comments from my account.
            modlog: Access the moderation log in subreddits I moderate.
            modposts: >-
              Approve, remove, mark nsfw, and distinguish content in subreddits
              I moderate.
            modflair: Manage and assign flair in subreddits I moderate.
            save: Save and unsave comments and submissions.
            modothers: Invite or remove other moderators from subreddits I moderate.
            read: Access posts and comments through my account.
            privatemessages: Access my inbox and send private messages to other users.
            report: >-
              Report content for rules violations. Hide &amp; show individual
              submissions.
            identity: Access my reddit username and signup date.
            livemanage: Manage settings and contributors of live threads I contribute to.
            account: >-
              Update preferences and related account information. Will not have
              access to your email or password.
            modtraffic: Access traffic stats in subreddits I moderate.
            wikiread: Read wiki pages through my account
            edit: Edit and delete my comments and submissions.
            modwiki: >-
              Change editors and visibility of wiki pages in subreddits I
              moderate.
            modself: >-
              Accept invitations to moderate a subreddit. Remove myself as a
              moderator or contributor of subreddits I moderate or contribute
              to.
            history: >-
              Access my voting history and comments or submissions I've saved or
              hidden.
            flair: Select my subreddit flair. Change link flair on my submissions.
        implicit:
          authorizationUrl: 'https://www.reddit.com/api/v1/authorize'
          scopes: *ref_0
    oauthClientSecret:
      type: http
      scheme: basic
tags:
  - name: account
  - name: captcha
  - name: collections
  - name: emoji
  - name: flair
  - name: reddit gold
  - name: links & comments
  - name: listings
  - name: live threads
    description: >-
      Real-time updates on reddit. 

      In addition to the standard reddit API, WebSockets play a huge role in
      reddit live. Receiving push notification of changes to the thread via
      websockets is much better than polling the thread repeatedly. 

      To connect to the websocket server, fetch /live/thread/about.json and get
      the websocket_url field. The websocket URL expires after a period of time;
      if it does, fetch a new one from that endpoint. 

      Once connected to the socket, a variety of messages can come in. All
      messages will be in text frames containing a JSON object with two keys:
      type and payload. Live threads can send messages with many types: 
       
      update - a new update has been posted in the thread. the payload contains
      the JSON representation of the update. 

      activity - periodic update of the viewer counts for the thread. 

      settings - the thread's settings have changed. the payload is an object
      with each key being a property of the thread (as in about.json) and its
      new value. 

      delete - an update has been deleted (removed from the thread). the payload
      is the ID of the deleted update. 

      strike - an update has been stricken (marked incorrect and crossed out).
      the payload is the ID of the stricken update. 

      embeds_ready - a previously posted update has been parsed and embedded
      media is available for it now. the payload contains a liveupdate_id and
      list of embeds to add to it. 

      complete - the thread has been marked complete. no further updates will be
      sent.  

      See /r/live for more information.  
  - name: private messages
  - name: misc
  - name: moderation
  - name: new modmail
  - name: modnote
  - name: multis
  - name: search
  - name: subreddits
  - name: users
  - name: widgets
  - name: wiki
paths:
  /api/v1/access_token:
    post:
      operationId: POST_api_v1_access_token
      summary: Complete an OAuth flow to receive a bearer token
      servers:
        - url: 'https://www.reddit.com'
          description: Accepts authentication requests.
      security:
        - oauthClientSecret: []
  /api/v1/revoke_token:
    post:
      operationId: POST_api_v1_revoke_token
      summary: Revokes a bearer token so that it cannot be used anymore
      servers:
        - url: 'https://www.reddit.com'
          description: Accepts authentication requests.
      security:
        - oauthClientSecret: []
  /api/v1/me.json:
    get:
      operationId: GET_api_v1_me
      security:
        - redditOAuth:
            - identity
      description: Returns the identity of the user.
      tags:
        - account
  /api/v1/me/karma.json:
    get:
      operationId: GET_api_v1_me_karma
      security:
        - redditOAuth:
            - mysubreddits
      description: Return a breakdown of subreddit karma.
      tags:
        - account
  /api/v1/me/prefs.json:
    get:
      operationId: GET_api_v1_me_prefs
      security:
        - redditOAuth:
            - identity
      description: Return the preference settings of the logged in user
      tags:
        - account
    patch:
      operationId: PATCH_api_v1_me_prefs
      security:
        - redditOAuth:
            - account
      description: ''
      tags:
        - account
  /api/v1/me/trophies.json:
    get:
      operationId: GET_api_v1_me_trophies
      security:
        - redditOAuth:
            - identity
      description: Return a list of trophies for the current user.
      tags:
        - account
  /prefs/friends.json:
    get:
      operationId: GET_prefs_friends
      security: &ref_1
        - redditOAuth:
            - read
      description: This endpoint is a listing.
      tags: &ref_2
        - account
  /prefs/blocked.json:
    get:
      operationId: GET_prefs_blocked
      security: *ref_1
      description: This endpoint is a listing.
      tags: *ref_2
  /prefs/messaging.json:
    get:
      operationId: GET_prefs_messaging
      security: *ref_1
      description: This endpoint is a listing.
      tags: *ref_2
  /prefs/trusted.json:
    get:
      operationId: GET_prefs_trusted
      security: *ref_1
      description: This endpoint is a listing.
      tags: *ref_2
  /api/v1/me/friends.json:
    get:
      operationId: GET_api_v1_me_friends
      security: *ref_1
      description: This endpoint is a listing.
      tags: *ref_2
  /api/v1/me/blocked.json:
    get:
      operationId: GET_api_v1_me_blocked
      security: *ref_1
      description: This endpoint is a listing.
      tags: *ref_2
  /api/needs_captcha.json:
    get:
      operationId: GET_api_needs_captcha
      security:
        - redditOAuth:
            - any
      description: Check whether ReCAPTCHAs are needed for API methods
      tags:
        - captcha
  /api/v1/collections/add_post_to_collection.json:
    post:
      operationId: POST_api_v1_collections_add_post_to_collection
      security:
        - redditOAuth:
            - modposts
      description: Add a post to a collection
      tags:
        - collections
  /api/v1/collections/collection.json:
    get:
      operationId: GET_api_v1_collections_collection
      security:
        - redditOAuth:
            - read
      description: Fetch a collection including all the links
      tags:
        - collections
  /api/v1/collections/create_collection.json:
    post:
      operationId: POST_api_v1_collections_create_collection
      security:
        - redditOAuth:
            - modposts
      description: Create a collection
      tags:
        - collections
  /api/v1/collections/delete_collection.json:
    post:
      operationId: POST_api_v1_collections_delete_collection
      security:
        - redditOAuth:
            - modposts
      description: Delete a collection
      tags:
        - collections
  /api/v1/collections/follow_collection.json:
    post:
      operationId: POST_api_v1_collections_follow_collection
      security:
        - redditOAuth:
            - subscribe
      description: >-
        Follow or unfollow a collection 

        To follow, follow should be True. To unfollow, follow should be False.
        The user must have access to the subreddit to be able to follow a
        collection within it.
      tags:
        - collections
  /api/v1/collections/remove_post_in_collection.json:
    post:
      operationId: POST_api_v1_collections_remove_post_in_collection
      security:
        - redditOAuth:
            - modposts
      description: Remove a post from a collection
      tags:
        - collections
  /api/v1/collections/reorder_collection.json:
    post:
      operationId: POST_api_v1_collections_reorder_collection
      security:
        - redditOAuth:
            - modposts
      description: Reorder posts in a collection
      tags:
        - collections
  /api/v1/collections/subreddit_collections.json:
    get:
      operationId: GET_api_v1_collections_subreddit_collections
      security:
        - redditOAuth:
            - read
      description: Fetch collections for the subreddit
      tags:
        - collections
  /api/v1/collections/update_collection_description.json:
    post:
      operationId: POST_api_v1_collections_update_collection_description
      security:
        - redditOAuth:
            - modposts
      description: Update a collection's description
      tags:
        - collections
  /api/v1/collections/update_collection_display_layout.json:
    post:
      operationId: POST_api_v1_collections_update_collection_display_layout
      security:
        - redditOAuth:
            - modposts
      description: Update a collection's display layout
      tags:
        - collections
  /api/v1/collections/update_collection_title.json:
    post:
      operationId: POST_api_v1_collections_update_collection_title
      security:
        - redditOAuth:
            - modposts
      description: Update a collection's title
      tags:
        - collections
  '/api/v1/{subreddit}/emoji.json':
    post:
      operationId: 'POST_api_v1_{subreddit}_emoji.json'
      security:
        - redditOAuth:
            - structuredstyles
      description: >-
        Add an emoji to the DB by posting a message on emoji_upload_q. A job
        processor that listens on a queue, uses the s3_key provided in the
        request to locate the image in S3 Temp Bucket and moves it to the PERM
        bucket. It also adds it to the DB using name as the column and
        sr_fullname as the key and sends the status on the websocket URL that is
        provided as part of this response. 

        This endpoint should also be used to update custom subreddit emojis with
        new images. If only the permissions on an emoji require updating the
        POST_emoji_permissions endpoint should be requested, instead.
      tags:
        - emoji
  '/api/v1/{subreddit}/emoji/{emoji_name}.json':
    delete:
      operationId: 'DELETE_api_v1_{subreddit}_emoji_{emoji_name}'
      security:
        - redditOAuth:
            - structuredstyles
      description: >-
        Delete a Subreddit emoji. Remove the emoji from Cassandra and purge the
        assets from S3 and the image resizing provider.
      tags:
        - emoji
  '/api/v1/{subreddit}/emoji_asset_upload_s3.json':
    post:
      operationId: 'POST_api_v1_{subreddit}_emoji_asset_upload_s3.json'
      security:
        - redditOAuth:
            - structuredstyles
      description: >-
        Acquire and return an upload lease to s3 temp bucket. The return value
        of this function is a json object containing credentials for uploading
        assets to S3 bucket, S3 url for upload request and the key to use for
        uploading. Using this lease the client will upload the emoji image to S3
        temp bucket (included as part of the S3 URL). 

        This lease is used by S3 to verify that the upload is authorized.
      tags:
        - emoji
  '/api/v1/{subreddit}/emoji_custom_size.json':
    post:
      operationId: 'POST_api_v1_{subreddit}_emoji_custom_size'
      security:
        - redditOAuth:
            - structuredstyles
      description: |-
        Set custom emoji size. 
        Omitting width or height will disable custom emoji sizing.
      tags:
        - emoji
  '/api/v1/{subreddit}/emojis/all.json':
    get:
      operationId: 'GET_api_v1_{subreddit}_emojis_all'
      security:
        - redditOAuth:
            - read
      description: >-
        Get all emojis for a SR. The response inclueds snoomojis as well as
        emojis for the SR specified in the request. 

        The response has 2 keys: - snoomojis - SR emojis
      tags:
        - emoji
  '/r/{subreddit}/api/clearflairtemplates.json':
    post:
      operationId: POST_api_clearflairtemplates
      security:
        - redditOAuth:
            - modflair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/deleteflair.json':
    post:
      operationId: POST_api_deleteflair
      security:
        - redditOAuth:
            - modflair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/deleteflairtemplate.json':
    post:
      operationId: POST_api_deleteflairtemplate
      security:
        - redditOAuth:
            - modflair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/flair.json':
    post:
      operationId: POST_api_flair
      security:
        - redditOAuth:
            - modflair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/flair_template_order.json':
    patch:
      operationId: PATCH_api_flair_template_order
      security:
        - redditOAuth:
            - modflair
      description: >-
        Update the order of flair templates in the specified subreddit. 

        Order should contain every single flair id for that flair type; omitting
        any id will result in a loss of data.
      tags:
        - flair
  '/r/{subreddit}/api/flairconfig.json':
    post:
      operationId: POST_api_flairconfig
      security:
        - redditOAuth:
            - modflair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/flaircsv.json':
    post:
      operationId: POST_api_flaircsv
      security:
        - redditOAuth:
            - modflair
      description: >-
        Change the flair of multiple users in the same subreddit with a single
        API call. 

        Requires a string 'flair_csv' which has up to 100 lines of the form
        'user,flairtext,cssclass' (Lines beyond the 100th are ignored). 

        If both cssclass and flairtext are the empty string for a given user,
        instead clears that user's flair. 

        Returns an array of objects indicating if each flair setting was
        applied, or a reason for the failure.
      tags:
        - flair
  '/r/{subreddit}/api/flairlist.json':
    get:
      operationId: GET_api_flairlist
      security:
        - redditOAuth:
            - modflair
      description: This endpoint is a listing.
      tags:
        - flair
  '/r/{subreddit}/api/flairselector.json':
    post:
      operationId: POST_api_flairselector
      security:
        - redditOAuth:
            - flair
      description: >-
        Return information about a users's flair options. 

        If link is given, return link flair options for an existing link. If
        is_newlink is True, return link flairs options for a new link
        submission. Otherwise, return user flair options for this subreddit. 

        The logged in user's flair is also returned. Subreddit moderators may
        give a user by name to instead retrieve that user's flair.
      tags:
        - flair
  '/r/{subreddit}/api/flairtemplate.json':
    post:
      operationId: POST_api_flairtemplate
      security:
        - redditOAuth:
            - modflair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/flairtemplate_v2.json':
    post:
      operationId: POST_api_flairtemplate_v2
      security:
        - redditOAuth:
            - modflair
      description: |-
        Create or update a flair template. 
        This new endpoint is primarily used for the redesign.
      tags:
        - flair
  '/r/{subreddit}/api/link_flair.json':
    get:
      operationId: GET_api_link_flair
      security:
        - redditOAuth:
            - flair
      description: >-
        Return list of available link flair for the current subreddit. 

        Will not return flair if the user cannot set their own link flair and
        they are not a moderator that can set flair.
      tags:
        - flair
  '/r/{subreddit}/api/link_flair_v2.json':
    get:
      operationId: GET_api_link_flair_v2
      security:
        - redditOAuth:
            - flair
      description: >-
        Return list of available link flair for the current subreddit. 

        Will not return flair if the user cannot set their own link flair and
        they are not a moderator that can set flair.
      tags:
        - flair
  '/r/{subreddit}/api/selectflair.json':
    post:
      operationId: POST_api_selectflair
      security:
        - redditOAuth:
            - flair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/setflairenabled.json':
    post:
      operationId: POST_api_setflairenabled
      security:
        - redditOAuth:
            - flair
      description: ''
      tags:
        - flair
  '/r/{subreddit}/api/user_flair.json':
    get:
      operationId: GET_api_user_flair
      security:
        - redditOAuth:
            - flair
      description: >-
        Return list of available user flair for the current subreddit. 

        Will not return flair if flair is disabled on the subreddit, the user
        cannot set their own flair, or they are not a moderator that can set
        flair.
      tags:
        - flair
  '/r/{subreddit}/api/user_flair_v2.json':
    get:
      operationId: GET_api_user_flair_v2
      security:
        - redditOAuth:
            - flair
      description: >-
        Return list of available user flair for the current subreddit. 

        If user is not a mod of the subreddit, this endpoint filters out
        mod_only templates.
      tags:
        - flair
  '/api/v1/gold/gild/{fullname}.json':
    post:
      operationId: 'POST_api_v1_gold_gild_{fullname}'
      security:
        - redditOAuth:
            - creddits
      description: ''
      tags:
        - reddit gold
  '/api/v1/gold/give/{username}.json':
    post:
      operationId: 'POST_api_v1_gold_give_{username}'
      security:
        - redditOAuth:
            - creddits
      description: ''
      tags:
        - reddit gold
  /api/comment.json:
    post:
      operationId: POST_api_comment
      security:
        - redditOAuth:
            - any
      description: >-
        Submit a new comment or reply to a message. 

        parent is the fullname of the thing being replied to. Its value changes
        the kind of object created by this request: 
         
        the fullname of a Link: a top-level comment in that Link's thread.
        (requires submit scope) 

        the fullname of a Comment: a comment reply to that comment. (requires
        submit scope) 

        the fullname of a Message: a message reply to that message. (requires
        privatemessages scope)  

        text should be the raw markdown body of the comment or message. 

        To start a new message thread, use /api/compose.
      tags:
        - links & comments
  /api/del.json:
    post:
      operationId: POST_api_del
      security:
        - redditOAuth:
            - edit
      description: Delete a Link or Comment.
      tags:
        - links & comments
  /api/editusertext.json:
    post:
      operationId: POST_api_editusertext
      security:
        - redditOAuth:
            - edit
      description: Edit the body text of a comment or self-post.
      tags:
        - links & comments
  /api/event_post_time.json:
    post:
      operationId: POST_api_event_post_time
      security:
        - redditOAuth:
            - modposts
      description: >-
        Add or modify post event times. To remove event info leave these fields
        empty.
      tags:
        - links & comments
  /api/follow_post.json:
    post:
      operationId: POST_api_follow_post
      security:
        - redditOAuth:
            - subscribe
      description: >-
        Follow or unfollow a post. 

        To follow, follow should be True. To unfollow, follow should be False.
        The user must have access to the subreddit to be able to follow a post
        within it.
      tags:
        - links & comments
  /api/hide.json:
    post:
      operationId: POST_api_hide
      security:
        - redditOAuth:
            - report
      description: |-
        Hide a link. 
        This removes it from the user's default view of subreddit listings. 
        See also: /api/unhide.
      tags:
        - links & comments
  '/r/{subreddit}/api/info.json':
    get:
      operationId: GET_api_info
      security:
        - redditOAuth:
            - read
      description: |-
        Return a listing of things specified by their fullnames. 
        Only Links, Comments, and Subreddits are allowed.
      tags:
        - links & comments
  /api/lock.json:
    post:
      operationId: POST_api_lock
      security:
        - redditOAuth:
            - modposts
      description: |-
        Lock a link or comment. 
        Prevents a post or new child comments from receiving new comments. 
        See also: /api/unlock.
      tags:
        - links & comments
  /api/marknsfw.json:
    post:
      operationId: POST_api_marknsfw
      security:
        - redditOAuth:
            - modposts
      description: |-
        Mark a link NSFW. 
        See also: /api/unmarknsfw.
      tags:
        - links & comments
  /api/morechildren.json:
    get:
      operationId: GET_api_morechildren
      security:
        - redditOAuth:
            - read
      description: >-
        Retrieve additional comments omitted from a base comment tree. 

        When a comment tree is rendered, the most relevant comments are selected
        for display first. Remaining comments are stubbed out with
        "MoreComments" links. This API call is used to retrieve the additional
        comments represented by those stubs, up to 100 at a time. 

        The two core parameters required are link and children. link is the
        fullname of the link whose comments are being fetched. children is a
        comma-delimited list of comment ID36s that need to be fetched. 

        If id is passed, it should be the ID of the MoreComments object this
        call is replacing. This is needed only for the HTML UI's purposes and is
        optional otherwise. 

        NOTE: you may only make one request at a time to this API endpoint.
        Higher concurrency will result in an error being returned. 

        If limit_children is True, only return the children requested. 

        depth is the maximum depth of subtrees in the thread.
      tags:
        - links & comments
  /api/report.json:
    post:
      operationId: POST_api_report
      security:
        - redditOAuth:
            - report
      description: >-
        Report a link, comment or message. Reporting a thing brings it to the
        attention of the subreddit's moderators. Reporting a message sends it to
        a system for admin review. For links and comments, the thing is
        implicitly hidden as well (see /api/hide for details). 

        See /r/{subreddit}/about/rules for for more about subreddit rules, and
        /r/{subreddit}/about for more about free_form_reports.
      tags:
        - links & comments
  /api/report_award.json:
    post:
      operationId: POST_api_report_award
      security:
        - redditOAuth:
            - report
      description: >-
        Report an award. Reporting an award brings it to the attention of a
        Reddit admin.
      tags:
        - links & comments
  /api/save.json:
    post:
      operationId: POST_api_save
      security:
        - redditOAuth:
            - save
      description: |-
        Save a link or comment. 
        Saved things are kept in the user's saved listing for later perusal. 
        See also: /api/unsave.
      tags:
        - links & comments
  /api/saved_categories.json:
    get:
      operationId: GET_api_saved_categories
      security:
        - redditOAuth:
            - save
      description: |-
        Get a list of categories in which things are currently saved. 
        See also: /api/save.
      tags:
        - links & comments
  /api/sendreplies.json:
    post:
      operationId: POST_api_sendreplies
      security:
        - redditOAuth:
            - edit
      description: >-
        Enable or disable inbox replies for a link or comment. 

        state is a boolean that indicates whether you are enabling or disabling
        inbox replies - true to enable, false to disable.
      tags:
        - links & comments
  /api/set_contest_mode.json:
    post:
      operationId: POST_api_set_contest_mode
      security:
        - redditOAuth:
            - modposts
      description: >-
        Set or unset "contest mode" for a link's comments. 

        state is a boolean that indicates whether you are enabling or disabling
        contest mode - true to enable, false to disable.
      tags:
        - links & comments
  /api/set_subreddit_sticky.json:
    post:
      operationId: POST_api_set_subreddit_sticky
      security:
        - redditOAuth:
            - modposts
      description: >-
        Set or unset a Link as the sticky in its subreddit. 

        state is a boolean that indicates whether to sticky or unsticky this
        post - true to sticky, false to unsticky. 

        The num argument is optional, and only used when stickying a post. It
        allows specifying a particular "slot" to sticky the post into, and if
        there is already a post stickied in that slot it will be replaced. If
        there is no post in the specified slot to replace, or num is None, the
        bottom-most slot will be used.
      tags:
        - links & comments
  /api/set_suggested_sort.json:
    post:
      operationId: POST_api_set_suggested_sort
      security:
        - redditOAuth:
            - modposts
      description: >-
        Set a suggested sort for a link. 

        Suggested sorts are useful to display comments in a certain preferred
        way for posts. For example, casual conversation may be better sorted by
        new by default, or AMAs may be sorted by Q&A. A sort of an empty string
        clears the default sort.
      tags:
        - links & comments
  /api/spoiler.json:
    post:
      operationId: POST_api_spoiler
      security:
        - redditOAuth:
            - modposts
      description: ''
      tags:
        - links & comments
  /api/store_visits.json:
    post:
      operationId: POST_api_store_visits
      security:
        - redditOAuth:
            - save
      description: '*Requires a subscription to [reddit premium]'
      tags:
        - links & comments
  /api/submit.json:
    post:
      operationId: POST_api_submit
      security:
        - redditOAuth:
            - submit
      description: >-
        Submit a link to a subreddit. 

        Submit will create a link or self-post in the subreddit sr with the
        title title. If kind is "link", then url is expected to be a valid URL
        to link to. Otherwise, text, if present, will be the body of the
        self-post unless richtext_json is present, in which case it will be
        converted into the body of the self-post. An error is thrown if both
        text and richtext_json are present. 

        If a link with the same URL has already been submitted to the specified
        subreddit an error will be returned unless resubmit is true. extension
        is used for determining which view-type (e.g. json, compact etc.) to use
        for the redirect that is generated if the resubmit error occurs.
      tags:
        - links & comments
  /api/unhide.json:
    post:
      operationId: POST_api_unhide
      security:
        - redditOAuth:
            - report
      description: |-
        Unhide a link. 
        See also: /api/hide.
      tags:
        - links & comments
  /api/unlock.json:
    post:
      operationId: POST_api_unlock
      security:
        - redditOAuth:
            - modposts
      description: |-
        Unlock a link or comment. 
        Allow a post or comment to receive new comments. 
        See also: /api/lock.
      tags:
        - links & comments
  /api/unmarknsfw.json:
    post:
      operationId: POST_api_unmarknsfw
      security:
        - redditOAuth:
            - modposts
      description: |-
        Remove the NSFW marking from a link. 
        See also: /api/marknsfw.
      tags:
        - links & comments
  /api/unsave.json:
    post:
      operationId: POST_api_unsave
      security:
        - redditOAuth:
            - save
      description: |-
        Unsave a link or comment. 
        This removes the thing from the user's saved listings as well. 
        See also: /api/save.
      tags:
        - links & comments
  /api/unspoiler.json:
    post:
      operationId: POST_api_unspoiler
      security:
        - redditOAuth:
            - modposts
      description: ''
      tags:
        - links & comments
  /api/vote.json:
    post:
      operationId: POST_api_vote
      security:
        - redditOAuth:
            - vote
      description: >-
        Cast a vote on a thing. 

        id should be the fullname of the Link or Comment to vote on. 

        dir indicates the direction of the vote. Voting 1 is an upvote, -1 is a
        downvote, and 0 is equivalent to "un-voting" by clicking again on a
        highlighted arrow. 

        Note: votes must be cast by humans. That is, API clients proxying a
        human's action one-for-one are OK, but bots deciding how to vote on
        content or amplifying a human's vote are not. See the reddit rules for
        more details on what constitutes vote cheating.
      tags:
        - links & comments
  '/best{read}.json':
    get:
      operationId: GET_best
      security:
        - redditOAuth:
            - read
      description: This endpoint is a listing.
      tags:
        - listings
  '/by_id/{names}.json':
    get:
      operationId: 'GET_by_id_{names}'
      security:
        - redditOAuth:
            - read
      description: |-
        Get a listing of links by fullname. 
        names is a list of fullnames for links separated by commas or spaces.
      tags:
        - listings
  '/r/{subreddit}/comments/{article}{read}.json':
    get:
      operationId: 'GET_comments_{article}'
      security:
        - redditOAuth:
            - read
      description: >-
        Get the comment tree for a given Link article. 

        If supplied, comment is the ID36 of a comment in the comment tree for
        article. This comment will be the (highlighted) focal point of the
        returned view and context will be the number of parents shown. 

        depth is the maximum depth of subtrees in the thread. 

        limit is the maximum number of comments to return. 

        See also: /api/morechildren and /api/comment.
      tags:
        - listings
  '/duplicates/{article}{read}.json':
    get:
      operationId: 'GET_duplicates_{article}'
      security:
        - redditOAuth:
            - read
      description: |-
        Return a list of other submissions of the same URL 
        This endpoint is a listing.
      tags:
        - listings
  '/r/{subreddit}/hot{read}.json':
    get:
      operationId: GET_hot
      security:
        - redditOAuth:
            - read
      description: This endpoint is a listing.
      tags:
        - listings
  '/r/{subreddit}/new{read}.json':
    get:
      operationId: GET_new
      security:
        - redditOAuth:
            - read
      description: This endpoint is a listing.
      tags:
        - listings
  '/r/{subreddit}/random.json':
    get:
      operationId: GET_random
      security:
        - redditOAuth:
            - read
      description: The Serendipity button
      tags:
        - listings
  '/r/{subreddit}/rising{read}.json':
    get:
      operationId: GET_rising
      security:
        - redditOAuth:
            - read
      description: This endpoint is a listing.
      tags:
        - listings
  '/r/{subreddit}/top.json':
    get:
      operationId: GET_top
      security: &ref_10
        - redditOAuth:
            - read
      description: This endpoint is a listing.
      tags: &ref_11
        - listings
  '/r/{subreddit}/controversial.json':
    get:
      operationId: GET_controversial
      security: *ref_10
      description: This endpoint is a listing.
      tags: *ref_11
  '/api/live/by_id/{names}.json':
    get:
      operationId: 'GET_api_live_by_id_{names}'
      security:
        - redditOAuth:
            - read
      description: Get a listing of live events by id.
      tags:
        - live threads
  /api/live/create.json:
    post:
      operationId: POST_api_live_create
      security:
        - redditOAuth:
            - submit
      description: >-
        Create a new live thread. 

        Once created, the initial settings can be modified with
        /api/live/thread/edit and new updates can be posted with
        /api/live/thread/update.
      tags:
        - live threads
  /api/live/happening_now.json:
    get:
      operationId: GET_api_live_happening_now
      security:
        - redditOAuth:
            - read
      description: >-
        Get some basic information about the currently featured live thread. 

        Returns an empty 204 response for api requests if no thread is currently
        featured. 

        See also: /api/live/thread/about.
      tags:
        - live threads
  '/api/live/{thread}/accept_contributor_invite.json':
    post:
      operationId: 'POST_api_live_{thread}_accept_contributor_invite'
      security:
        - redditOAuth:
            - livemanage
      description: |-
        Accept a pending invitation to contribute to the thread. 
        See also: /api/live/thread/leave_contributor.
      tags:
        - live threads
  '/api/live/{thread}/close_thread.json':
    post:
      operationId: 'POST_api_live_{thread}_close_thread'
      security:
        - redditOAuth:
            - livemanage
      description: |-
        Permanently close the thread, disallowing future updates. 
        Requires the close permission for this thread.
      tags:
        - live threads
  '/api/live/{thread}/delete_update.json':
    post:
      operationId: 'POST_api_live_{thread}_delete_update'
      security:
        - redditOAuth:
            - edit
      description: >-
        Delete an update from the thread. 

        Requires that specified update must have been authored by the user or
        that you have the edit permission for this thread. 

        See also: /api/live/thread/update.
      tags:
        - live threads
  '/api/live/{thread}/edit.json':
    post:
      operationId: 'POST_api_live_{thread}_edit'
      security:
        - redditOAuth:
            - livemanage
      description: |-
        Configure the thread. 
        Requires the settings permission for this thread. 
        See also: /live/thread/about.json.
      tags:
        - live threads
  '/api/live/{thread}/hide_discussion.json':
    post:
      operationId: 'POST_api_live_{thread}_hide_discussion'
      security:
        - redditOAuth:
            - livemanage
      description: |-
        Hide a linked comment thread from the discussions sidebar and listing. 
        Requires the discussions permission for this thread. 
        See also: /api/live/thread/unhide_discussion.
      tags:
        - live threads
  '/api/live/{thread}/invite_contributor.json':
    post:
      operationId: 'POST_api_live_{thread}_invite_contributor'
      security:
        - redditOAuth:
            - livemanage
      description: >-
        Invite another user to contribute to the thread. 

        Requires the manage permission for this thread. If the recipient accepts
        the invite, they will be granted the permissions specified. 

        See also: /api/live/thread/accept_contributor_invite, and
        /api/live/thread/rm_contributor_invite.
      tags:
        - live threads
  '/api/live/{thread}/leave_contributor.json':
    post:
      operationId: 'POST_api_live_{thread}_leave_contributor'
      security:
        - redditOAuth:
            - livemanage
      description: >-
        Abdicate contributorship of the thread. 

        See also: /api/live/thread/accept_contributor_invite, and
        /api/live/thread/invite_contributor.
      tags:
        - live threads
  '/api/live/{thread}/report.json':
    post:
      operationId: 'POST_api_live_{thread}_report'
      security:
        - redditOAuth:
            - report
      description: Report the thread for violating the rules of reddit.
      tags:
        - live threads
  '/api/live/{thread}/rm_contributor.json':
    post:
      operationId: 'POST_api_live_{thread}_rm_contributor'
      security:
        - redditOAuth:
            - livemanage
      description: |-
        Revoke another user's contributorship. 
        Requires the manage permission for this thread. 
        See also: /api/live/thread/invite_contributor.
      tags:
        - live threads
  '/api/live/{thread}/rm_contributor_invite.json':
    post:
      operationId: 'POST_api_live_{thread}_rm_contributor_invite'
      security:
        - redditOAuth:
            - livemanage
      description: |-
        Revoke an outstanding contributor invite. 
        Requires the manage permission for this thread. 
        See also: /api/live/thread/invite_contributor.
      tags:
        - live threads
  '/api/live/{thread}/set_contributor_permissions.json':
    post:
      operationId: 'POST_api_live_{thread}_set_contributor_permissions'
      security:
        - redditOAuth:
            - livemanage
      description: >-
        Change a contributor or contributor invite's permissions. 

        Requires the manage permission for this thread. 

        See also: /api/live/thread/invite_contributor and
        /api/live/thread/rm_contributor.
      tags:
        - live threads
  '/api/live/{thread}/strike_update.json':
    post:
      operationId: 'POST_api_live_{thread}_strike_update'
      security:
        - redditOAuth:
            - edit
      description: >-
        Strike (mark incorrect and cross out) the content of an update. 

        Requires that specified update must have been authored by the user or
        that you have the edit permission for this thread. 

        See also: /api/live/thread/update.
      tags:
        - live threads
  '/api/live/{thread}/unhide_discussion.json':
    post:
      operationId: 'POST_api_live_{thread}_unhide_discussion'
      security:
        - redditOAuth:
            - livemanage
      description: >-
        Unhide a linked comment thread from the discussions sidebar and
        listing.. 

        Requires the discussions permission for this thread. 

        See also: /api/live/thread/hide_discussion.
      tags:
        - live threads
  '/api/live/{thread}/update.json':
    post:
      operationId: 'POST_api_live_{thread}_update'
      security:
        - redditOAuth:
            - submit
      description: >-
        Post an update to the thread. 

        Requires the update permission for this thread. 

        See also: /api/live/thread/strike_update, and
        /api/live/thread/delete_update.
      tags:
        - live threads
  '/live/{thread}{read}.json':
    get:
      operationId: 'GET_live_{thread}'
      security:
        - redditOAuth:
            - read
      description: |-
        Get a list of updates posted in this thread. 
        See also: /api/live/thread/update. 
        This endpoint is a listing.
      tags:
        - live threads
  '/live/{thread}/about.json':
    get:
      operationId: 'GET_live_{thread}_about'
      security:
        - redditOAuth:
            - read
      description: |-
        Get some basic information about the live thread. 
        See also: /api/live/thread/edit.
      tags:
        - live threads
  '/live/{thread}/contributors.json':
    get:
      operationId: 'GET_live_{thread}_contributors'
      security:
        - redditOAuth:
            - read
      description: >-
        Get a list of users that contribute to this thread. 

        See also: /api/live/thread/invite_contributor, and
        /api/live/thread/rm_contributor.
      tags:
        - live threads
  '/live/{thread}/discussions{read}.json':
    get:
      operationId: 'GET_live_{thread}_discussions'
      security:
        - redditOAuth:
            - read
      description: |-
        Get a list of reddit submissions linking to this thread. 
        This endpoint is a listing.
      tags:
        - live threads
  '/live/{thread}/updates/{update_id}.json':
    get:
      operationId: 'GET_live_{thread}_updates_{update_id}'
      security:
        - redditOAuth:
            - read
      description: Get details about a specific update in a live thread.
      tags:
        - live threads
  /api/block.json:
    post:
      operationId: POST_api_block
      security:
        - redditOAuth:
            - privatemessages
      description: For blocking the author of a thing via inbox.
      tags:
        - private messages
  /api/collapse_message.json:
    post:
      operationId: POST_api_collapse_message
      security:
        - redditOAuth:
            - privatemessages
      description: |-
        Collapse a message 
        See also: /api/uncollapse_message
      tags:
        - private messages
  /api/compose.json:
    post:
      operationId: POST_api_compose
      security:
        - redditOAuth:
            - privatemessages
      description: Handles message composition under /message/compose.
      tags:
        - private messages
  /api/del_msg.json:
    post:
      operationId: POST_api_del_msg
      security:
        - redditOAuth:
            - privatemessages
      description: Delete messages from the recipient's view of their inbox.
      tags:
        - private messages
  /api/read_all_messages.json:
    post:
      operationId: POST_api_read_all_messages
      security:
        - redditOAuth:
            - privatemessages
      description: >-
        Queue up marking all messages for a user as read. 

        This may take some time, and returns 202 to acknowledge acceptance of
        the request.
      tags:
        - private messages
  /api/read_message.json:
    post:
      operationId: POST_api_read_message
      security:
        - redditOAuth:
            - privatemessages
      description: ''
      tags:
        - private messages
  /api/unblock_subreddit.json:
    post:
      operationId: POST_api_unblock_subreddit
      security:
        - redditOAuth:
            - privatemessages
      description: ''
      tags:
        - private messages
  /api/uncollapse_message.json:
    post:
      operationId: POST_api_uncollapse_message
      security:
        - redditOAuth:
            - privatemessages
      description: |-
        Uncollapse a message 
        See also: /api/collapse_message
      tags:
        - private messages
  /api/unread_message.json:
    post:
      operationId: POST_api_unread_message
      security:
        - redditOAuth:
            - privatemessages
      description: ''
      tags:
        - private messages
  /message/inbox.json:
    get:
      operationId: GET_message_inbox
      security: &ref_20
        - redditOAuth:
            - privatemessages
      description: This endpoint is a listing.
      tags: &ref_21
        - private messages
  /message/unread.json:
    get:
      operationId: GET_message_unread
      security: *ref_20
      description: This endpoint is a listing.
      tags: *ref_21
  /message/sent.json:
    get:
      operationId: GET_message_sent
      security: *ref_20
      description: This endpoint is a listing.
      tags: *ref_21
  '/r/{subreddit}/api/saved_media_text.json':
    get:
      operationId: GET_api_saved_media_text
      security:
        - redditOAuth:
            - submit
      description: >-
        Retrieve the advisory text about saving media for relevant media links. 

        This endpoint returns a notice for display during the post submission
        process that is pertinent to media links.
      tags:
        - misc
  /api/v1/scopes.json:
    get:
      operationId: GET_api_v1_scopes
      security:
        - redditOAuth:
            - any
      description: >-
        Retrieve descriptions of reddit's OAuth2 scopes. 

        If no scopes are given, information on all scopes are returned. 

        Invalid scope(s) will result in a 400 error with body that indicates the
        invalid scope(s).
      tags:
        - misc
  '/r/{subreddit}/about/log{modlog}.json':
    get:
      operationId: GET_about_log
      security:
        - redditOAuth:
            - modlog
      description: >-
        Get a list of recent moderation actions. 

        Moderator actions taken within a subreddit are logged. This listing is a
        view of that log with various filters to aid in analyzing the
        information. 

        The optional mod parameter can be a comma-delimited list of moderator
        names to restrict the results to, or the string a to restrict the
        results to admin actions taken within the subreddit. 

        The type parameter is optional and if sent limits the log entries
        returned to only those of the type specified. 

        This endpoint is a listing.
      tags:
        - moderation
  '/r/{subreddit}/about/reports.json':
    get:
      operationId: GET_about_reports
      security: &ref_31
        - redditOAuth:
            - read
      description: >-
        Return a listing of posts relevant to moderators. 
         
        reports: Things that have been reported. 

        spam: Things that have been marked as spam or otherwise removed. 

        modqueue: Things requiring moderator review, such as reported things and
        items caught by the spam filter. 

        unmoderated: Things that have yet to be approved/removed by a mod. 

        edited: Things that have been edited recently.  

        Requires the "posts" moderator permission for the subreddit. 

        This endpoint is a listing.
      tags: &ref_32
        - moderation
  '/r/{subreddit}/about/spam.json':
    get:
      operationId: GET_about_spam
      security: *ref_31
      description: >-
        Return a listing of posts relevant to moderators. 
         
        reports: Things that have been reported. 

        spam: Things that have been marked as spam or otherwise removed. 

        modqueue: Things requiring moderator review, such as reported things and
        items caught by the spam filter. 

        unmoderated: Things that have yet to be approved/removed by a mod. 

        edited: Things that have been edited recently.  

        Requires the "posts" moderator permission for the subreddit. 

        This endpoint is a listing.
      tags: *ref_32
  '/r/{subreddit}/about/modqueue.json':
    get:
      operationId: GET_about_modqueue
      security: *ref_31
      description: >-
        Return a listing of posts relevant to moderators. 
         
        reports: Things that have been reported. 

        spam: Things that have been marked as spam or otherwise removed. 

        modqueue: Things requiring moderator review, such as reported things and
        items caught by the spam filter. 

        unmoderated: Things that have yet to be approved/removed by a mod. 

        edited: Things that have been edited recently.  

        Requires the "posts" moderator permission for the subreddit. 

        This endpoint is a listing.
      tags: *ref_32
  '/r/{subreddit}/about/unmoderated.json':
    get:
      operationId: GET_about_unmoderated
      security: *ref_31
      description: >-
        Return a listing of posts relevant to moderators. 
         
        reports: Things that have been reported. 

        spam: Things that have been marked as spam or otherwise removed. 

        modqueue: Things requiring moderator review, such as reported things and
        items caught by the spam filter. 

        unmoderated: Things that have yet to be approved/removed by a mod. 

        edited: Things that have been edited recently.  

        Requires the "posts" moderator permission for the subreddit. 

        This endpoint is a listing.
      tags: *ref_32
  '/r/{subreddit}/about/edited.json':
    get:
      operationId: GET_about_edited
      security: *ref_31
      description: >-
        Return a listing of posts relevant to moderators. 
         
        reports: Things that have been reported. 

        spam: Things that have been marked as spam or otherwise removed. 

        modqueue: Things requiring moderator review, such as reported things and
        items caught by the spam filter. 

        unmoderated: Things that have yet to be approved/removed by a mod. 

        edited: Things that have been edited recently.  

        Requires the "posts" moderator permission for the subreddit. 

        This endpoint is a listing.
      tags: *ref_32
  '/r/{subreddit}/api/accept_moderator_invite.json':
    post:
      operationId: POST_api_accept_moderator_invite
      security:
        - redditOAuth:
            - modself
      description: >-
        Accept an invite to moderate the specified subreddit. 

        The authenticated user must have been invited to moderate the subreddit
        by one of its current moderators. 

        See also: /api/friend and /subreddits/mine.
      tags:
        - moderation
  /api/approve.json:
    post:
      operationId: POST_api_approve
      security:
        - redditOAuth:
            - modposts
      description: >-
        Approve a link or comment. 

        If the thing was removed, it will be re-inserted into appropriate
        listings. Any reports on the approved thing will be discarded. 

        See also: /api/remove.
      tags:
        - moderation
  /api/distinguish.json:
    post:
      operationId: POST_api_distinguish
      security:
        - redditOAuth:
            - modposts
      description: >-
        Distinguish a thing's author with a sigil. 

        This can be useful to draw attention to and confirm the identity of the
        user in the context of a link or comment of theirs. The options for
        distinguish are as follows: 
         
        yes - add a moderator distinguish ([M]). only if the user is a moderator
        of the subreddit the thing is in. 

        no - remove any distinguishes. 

        admin - add an admin distinguish ([A]). admin accounts only. 

        special - add a user-specific distinguish. depends on user.  

        The first time a top-level comment is moderator distinguished, the
        author of the link the comment is in reply to will get a notification in
        their inbox. 

        sticky is a boolean flag for comments, which will stick the distingushed
        comment to the top of all comments threads. If a comment is marked
        sticky, it will override any other stickied comment for that link (as
        only one comment may be stickied at a time.) Only top-level comments may
        be stickied.
      tags:
        - moderation
  /api/ignore_reports.json:
    post:
      operationId: POST_api_ignore_reports
      security:
        - redditOAuth:
            - modposts
      description: >-
        Prevent future reports on a thing from causing notifications. 

        Any reports made about a thing after this flag is set on it will not
        cause notifications or make the thing show up in the various moderation
        listings. 

        See also: /api/unignore_reports.
      tags:
        - moderation
  /api/leavecontributor.json:
    post:
      operationId: POST_api_leavecontributor
      security:
        - redditOAuth:
            - modself
      description: |-
        Abdicate approved user status in a subreddit. 
        See also: /api/friend.
      tags:
        - moderation
  /api/leavemoderator.json:
    post:
      operationId: POST_api_leavemoderator
      security:
        - redditOAuth:
            - modself
      description: |-
        Abdicate moderator status in a subreddit. 
        See also: /api/friend.
      tags:
        - moderation
  /api/mute_message_author.json:
    post:
      operationId: POST_api_mute_message_author
      security:
        - redditOAuth:
            - modcontributors
      description: For muting user via modmail.
      tags:
        - moderation
  /api/remove.json:
    post:
      operationId: POST_api_remove
      security:
        - redditOAuth:
            - modposts
      description: >-
        Remove a link, comment, or modmail message. 

        If the thing is a link, it will be removed from all subreddit listings.
        If the thing is a comment, it will be redacted and removed from all
        subreddit comment listings. 

        See also: /api/approve.
      tags:
        - moderation
  /api/show_comment.json:
    post:
      operationId: POST_api_show_comment
      security:
        - redditOAuth:
            - modposts
      description: >-
        Mark a comment that it should not be collapsed because of crowd
        control. 

        The comment could still be collapsed for other reasons.
      tags:
        - moderation
  /api/snooze_reports.json:
    post:
      operationId: POST_api_snooze_reports
      security:
        - redditOAuth:
            - modposts
      description: >-
        Prevent future reports on a thing from causing notifications. 

        For users who reported this thing (post, comment, etc) with the given
        report reason, reports from those users in the next 7 days will not be
        escalated to moderators. See also: /api/unsnooze_reports.
      tags:
        - moderation
  /api/unignore_reports.json:
    post:
      operationId: POST_api_unignore_reports
      security:
        - redditOAuth:
            - modposts
      description: |-
        Allow future reports on a thing to cause notifications. 
        See also: /api/ignore_reports.
      tags:
        - moderation
  /api/unmute_message_author.json:
    post:
      operationId: POST_api_unmute_message_author
      security:
        - redditOAuth:
            - modcontributors
      description: For unmuting user via modmail.
      tags:
        - moderation
  /api/unsnooze_reports.json:
    post:
      operationId: POST_api_unsnooze_reports
      security:
        - redditOAuth:
            - modposts
      description: >-
        For users whose reports were snoozed (see /api/snooze_reports), to go
        back to escalating future reports from those users.
      tags:
        - moderation
  /api/update_crowd_control_level.json:
    post:
      operationId: POST_api_update_crowd_control_level
      security:
        - redditOAuth:
            - modposts
      description: Change the post's crowd control level.
      tags:
        - moderation
  '/r/{subreddit}/stylesheet.json':
    get:
      operationId: GET_stylesheet
      security:
        - redditOAuth:
            - modconfig
      description: |-
        Redirect to the subreddit's stylesheet if one exists. 
        See also: /api/subreddit_stylesheet.
      tags:
        - moderation
  /api/mod/bulk_read.json:
    post:
      operationId: POST_api_mod_bulk_read
      security:
        - redditOAuth:
            - modmail
      description: >-
        Marks all conversations read for a particular conversation state within
        the passed list of subreddits.
      tags:
        - new modmail
  /api/mod/conversations.json:
    get:
      operationId: GET_api_mod_conversations
      security:
        - redditOAuth:
            - modmail
      description: Get conversations for a logged in user or subreddits
      tags:
        - new modmail
    post:
      operationId: POST_api_mod_conversations
      security:
        - redditOAuth:
            - modmail
      description: >-
        Creates a new conversation for a particular SR. 

        This endpoint will create a ModmailConversation object as well as the
        first ModmailMessage within the ModmailConversation object. 

        A note on to: 

        The to field for this endpoint is somewhat confusing. It can be: 
         
        A User, passed like "username" or "u/username" 

        A Subreddit, passed like "r/subreddit" 

        null  

        If to is null, it is currently inferred to mean either: 

        (A) if the current user is a mod with mail permission, this is an
        internal moderator discussion amongst themselves 

        (B) if the current user is NOT a mod with mail permission, the logged in
        user is communicating with the subreddit, as if to was set to the
        current logged in user 

        In this way to is a bit of a misnomer in modmail conversations. What it
        really means is the participant of the conversation who is not a mod of
        the subreddit. The conversation could have been created from that
        participant, or not.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id.json':
    get:
      operationId: 'GET_api_mod_conversations_:conversation_id'
      security:
        - redditOAuth:
            - modmail
      description: >-
        Returns all messages, mod actions and conversation metadata for a given
        conversation id
      tags:
        - new modmail
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id'
      security:
        - redditOAuth:
            - modmail
      description: >-
        Creates a new message for a particular conversation. 

        Workflow: (A) Validate params & check permissions (B) Create our local
        message in our conversation (C) Create the message in the participant
        system (legacy PM or the other subreddit's conversation)
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/approve.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_approve'
      security:
        - redditOAuth:
            - modmail
      description: Approve the non mod user associated with a particular conversation.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/archive.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_archive'
      security:
        - redditOAuth:
            - modmail
      description: Marks a conversation as archived.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/disapprove.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_disapprove'
      security:
        - redditOAuth:
            - modmail
      description: Disapprove the non mod user associated with a particular conversation.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/highlight.json':
    delete:
      operationId: 'DELETE_api_mod_conversations_:conversation_id_highlight'
      security:
        - redditOAuth:
            - modmail
      description: Removes a highlight from a conversation.
      tags:
        - new modmail
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_highlight'
      security:
        - redditOAuth:
            - modmail
      description: Marks a conversation as highlighted.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/mute.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_mute'
      security:
        - redditOAuth:
            - modmail
      description: Mutes the non mod user associated with a particular conversation.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/temp_ban.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_temp_ban'
      security:
        - redditOAuth:
            - modmail
      description: >-
        Temporary ban (switch from permanent to temporary ban) the non mod user
        associated with a particular conversation.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/unarchive.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_unarchive'
      security:
        - redditOAuth:
            - modmail
      description: Marks conversation as unarchived.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/unban.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_unban'
      security:
        - redditOAuth:
            - modmail
      description: Unban the non mod user associated with a particular conversation.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/unmute.json':
    post:
      operationId: 'POST_api_mod_conversations_:conversation_id_unmute'
      security:
        - redditOAuth:
            - modmail
      description: Unmutes the non mod user associated with a particular conversation.
      tags:
        - new modmail
  '/api/mod/conversations/:conversation_id/user.json':
    get:
      operationId: 'GET_api_mod_conversations_:conversation_id_user'
      security:
        - redditOAuth:
            - modmail
      description: >-
        Returns recent posts, comments and modmail conversations for a given
        user.
      tags:
        - new modmail
  /api/mod/conversations/read.json:
    post:
      operationId: POST_api_mod_conversations_read
      security:
        - redditOAuth:
            - modmail
      description: Marks a conversations as read for the user.
      tags:
        - new modmail
  /api/mod/conversations/subreddits.json:
    get:
      operationId: GET_api_mod_conversations_subreddits
      security:
        - redditOAuth:
            - modmail
      description: >-
        Returns a list of srs that the user moderates that are also enrolled in
        the new modmail
      tags:
        - new modmail
  /api/mod/conversations/unread.json:
    post:
      operationId: POST_api_mod_conversations_unread
      security:
        - redditOAuth:
            - modmail
      description: Marks conversations as unread for the user.
      tags:
        - new modmail
  /api/mod/conversations/unread/count.json:
    get:
      operationId: GET_api_mod_conversations_unread_count
      security:
        - redditOAuth:
            - modmail
      description: >-
        Endpoint to retrieve the unread conversation count by conversation
        state.
      tags:
        - new modmail
  /api/mod/notes.json:
    delete:
      operationId: DELETE_api_mod_notes
      security:
        - redditOAuth:
            - modnote
      description: |-
        Delete a mod user note where type=NOTE. 
        Parameters should be passed as query parameters.
      tags:
        - modnote
    get:
      operationId: GET_api_mod_notes
      security:
        - redditOAuth:
            - modnote
      description: Get mod notes for a specific user in a given subreddit.
      tags:
        - modnote
    post:
      operationId: POST_api_mod_notes
      security:
        - redditOAuth:
            - modnote
      description: Create a mod user note where type=NOTE.
      tags:
        - modnote
  /api/mod/notes/recent.json:
    get:
      operationId: GET_api_mod_notes_recent
      security:
        - redditOAuth:
            - modnote
      description: >-
        Fetch the most recent notes written by a moderator 

        Both parameters should be comma separated lists of equal lengths. The
        first subreddit will be paired with the first account to represent a
        query for a mod written note for that account in that subreddit and so
        forth for all subsequent pairs of subreddits and accounts. This request
        accepts up to 500 pairs of subreddit names and usernames. Parameters
        should be passed as query parameters. 

        The response will be a list of mod notes in the order that subreddits
        and accounts were given. If no note exist for a given subreddit/account
        pair, then null will take its place in the list.
      tags:
        - modnote
  /api/multi/copy.json:
    post:
      operationId: POST_api_multi_copy
      security:
        - redditOAuth:
            - subscribe
      description: >-
        Copy a multi. 

        Responds with 409 Conflict if the target already exists. 

        A "copied from ..." line will automatically be appended to the
        description.
      tags:
        - multis
  /api/multi/mine.json:
    get:
      operationId: GET_api_multi_mine
      security:
        - redditOAuth:
            - read
      description: Fetch a list of multis belonging to the current user.
      tags:
        - multis
  '/api/multi/user/{username}.json':
    get:
      operationId: 'GET_api_multi_user_{username}'
      security:
        - redditOAuth:
            - read
      description: Fetch a list of public multis belonging to username
      tags:
        - multis
  '/api/filter/{filterpath}.json':
    delete:
      operationId: 'DELETE_api_filter_{filterpath}'
      security:
        - redditOAuth:
            - subscribe
      description: Delete a multi.
      tags:
        - multis
    get:
      operationId: 'GET_api_filter_{filterpath}'
      security:
        - redditOAuth:
            - read
      description: Fetch a multi's data and subreddit list by name.
      tags:
        - multis
    post:
      operationId: 'POST_api_filter_{filterpath}'
      security:
        - redditOAuth:
            - subscribe
      description: Create a multi. Responds with 409 Conflict if it already exists.
      tags:
        - multis
    put:
      operationId: 'PUT_api_filter_{filterpath}'
      security:
        - redditOAuth:
            - subscribe
      description: Create or update a multi.
      tags:
        - multis
  '/api/multi/{multipath}/description.json':
    get:
      operationId: 'GET_api_multi_{multipath}_description'
      security:
        - redditOAuth:
            - read
      description: Get a multi's description.
      tags:
        - multis
    put:
      operationId: 'PUT_api_multi_{multipath}_description'
      security:
        - redditOAuth:
            - read
      description: Change a multi's markdown description.
      tags:
        - multis
  '/api/filter/{filterpath}/r/{srname}.json':
    delete:
      operationId: 'DELETE_api_filter_{filterpath}_r_{srname}'
      security:
        - redditOAuth:
            - subscribe
      description: Remove a subreddit from a multi.
      tags:
        - multis
    get:
      operationId: 'GET_api_filter_{filterpath}_r_{srname}'
      security:
        - redditOAuth:
            - read
      description: Get data about a subreddit in a multi.
      tags:
        - multis
    put:
      operationId: 'PUT_api_filter_{filterpath}_r_{srname}'
      security:
        - redditOAuth:
            - subscribe
      description: Add a subreddit to a multi.
      tags:
        - multis
  '/r/{subreddit}/search{read}.json':
    get:
      operationId: GET_search
      security:
        - redditOAuth:
            - read
      description: |-
        Search links page. 
        This endpoint is a listing.
      tags:
        - search
  '/r/{subreddit}/about/banned.json':
    get:
      operationId: GET_about_banned
      security: &ref_42
        - redditOAuth:
            - read
      description: This endpoint is a listing.
      tags: &ref_43
        - subreddits
  '/r/{subreddit}/about/muted.json':
    get:
      operationId: GET_about_muted
      security: *ref_42
      description: This endpoint is a listing.
      tags: *ref_43
  '/r/{subreddit}/about/wikibanned.json':
    get:
      operationId: GET_about_wikibanned
      security: *ref_42
      description: This endpoint is a listing.
      tags: *ref_43
  '/r/{subreddit}/about/contributors.json':
    get:
      operationId: GET_about_contributors
      security: *ref_42
      description: This endpoint is a listing.
      tags: *ref_43
  '/r/{subreddit}/about/wikicontributors.json':
    get:
      operationId: GET_about_wikicontributors
      security: *ref_42
      description: This endpoint is a listing.
      tags: *ref_43
  '/r/{subreddit}/about/moderators.json':
    get:
      operationId: GET_about_moderators
      security: *ref_42
      description: This endpoint is a listing.
      tags: *ref_43
  '/r/{subreddit}/api/delete_sr_banner.json':
    post:
      operationId: POST_api_delete_sr_banner
      security:
        - redditOAuth:
            - modconfig
      description: |-
        Remove the subreddit's custom mobile banner. 
        See also: /api/upload_sr_img.
      tags:
        - subreddits
  '/r/{subreddit}/api/delete_sr_header.json':
    post:
      operationId: POST_api_delete_sr_header
      security:
        - redditOAuth:
            - modconfig
      description: |-
        Remove the subreddit's custom header image. 
        The sitewide-default header image will be shown again after this call. 
        See also: /api/upload_sr_img.
      tags:
        - subreddits
  '/r/{subreddit}/api/delete_sr_icon.json':
    post:
      operationId: POST_api_delete_sr_icon
      security:
        - redditOAuth:
            - modconfig
      description: |-
        Remove the subreddit's custom mobile icon. 
        See also: /api/upload_sr_img.
      tags:
        - subreddits
  '/r/{subreddit}/api/delete_sr_img.json':
    post:
      operationId: POST_api_delete_sr_img
      security:
        - redditOAuth:
            - modconfig
      description: >-
        Remove an image from the subreddit's custom image set. 

        The image will no longer count against the subreddit's image limit.
        However, the actual image data may still be accessible for an
        unspecified amount of time. If the image is currently referenced by the
        subreddit's stylesheet, that stylesheet will no longer validate and
        won't be editable until the image reference is removed. 

        See also: /api/upload_sr_img.
      tags:
        - subreddits
  '/api/recommend/sr/{srnames}.json':
    get:
      operationId: 'GET_api_recommend_sr_{srnames}'
      security:
        - redditOAuth:
            - read
      description: >-
        DEPRECATED: Return subreddits recommended for the given subreddit(s). 

        Gets a list of subreddits recommended for srnames, filtering out any
        that appear in the optional omit param.
      tags:
        - subreddits
  /api/search_reddit_names.json:
    get:
      operationId: GET_api_search_reddit_names
      security:
        - redditOAuth:
            - read
      description: >-
        List subreddit names that begin with a query string. 

        Subreddits whose names begin with query will be returned. If
        include_over_18 is false, subreddits with over-18 content restrictions
        will be filtered from the results. 

        If include_unadvertisable is False, subreddits that have hide_ads set to
        True or are on the anti_ads_subreddits list will be filtered. 

        If exact is true, only an exact match will be returned. Exact matches
        are inclusive of over_18 subreddits, but not hide_ad subreddits when
        include_unadvertisable is False.
      tags:
        - subreddits
    post:
      operationId: POST_api_search_reddit_names
      security:
        - redditOAuth:
            - read
      description: >-
        List subreddit names that begin with a query string. 

        Subreddits whose names begin with query will be returned. If
        include_over_18 is false, subreddits with over-18 content restrictions
        will be filtered from the results. 

        If include_unadvertisable is False, subreddits that have hide_ads set to
        True or are on the anti_ads_subreddits list will be filtered. 

        If exact is true, only an exact match will be returned. Exact matches
        are inclusive of over_18 subreddits, but not hide_ad subreddits when
        include_unadvertisable is False.
      tags:
        - subreddits
  /api/search_subreddits.json:
    post:
      operationId: POST_api_search_subreddits
      security:
        - redditOAuth:
            - read
      description: >-
        List subreddits that begin with a query string. 

        Subreddits whose names begin with query will be returned. If
        include_over_18 is false, subreddits with over-18 content restrictions
        will be filtered from the results. 

        If include_unadvertisable is False, subreddits that have hide_ads set to
        True or are on the anti_ads_subreddits list will be filtered. 

        If exact is true, only an exact match will be returned. Exact matches
        are inclusive of over_18 subreddits, but not hide_ad subreddits when
        include_unadvertisable is False.
      tags:
        - subreddits
  /api/site_admin.json:
    post:
      operationId: POST_api_site_admin
      security:
        - redditOAuth:
            - modconfig
      description: >-
        Create or configure a subreddit. 

        If sr is specified, the request will attempt to modify the specified
        subreddit. If not, a subreddit with name name will be created. 

        This endpoint expects all values to be supplied on every request. If
        modifying a subset of options, it may be useful to get the current
        settings from /about/edit.json first. 

        For backwards compatibility, description is the sidebar text and
        public_description is the publicly visible subreddit description. 

        Most of the parameters for this endpoint are identical to options
        visible in the user interface and their meanings are best explained
        there. 

        See also: /about/edit.json.
      tags:
        - subreddits
  '/r/{subreddit}/api/submit_text.json':
    get:
      operationId: GET_api_submit_text
      security:
        - redditOAuth:
            - submit
      description: >-
        Get the submission text for the subreddit. 

        This text is set by the subreddit moderators and intended to be
        displayed on the submission form. 

        See also: /api/site_admin.
      tags:
        - subreddits
  /api/subreddit_autocomplete.json:
    get:
      operationId: GET_api_subreddit_autocomplete
      security:
        - redditOAuth:
            - read
      description: >-
        Return a list of subreddits and data for subreddits whose names start
        with 'query'. 

        Uses typeahead endpoint to recieve the list of subreddits names.
        Typeahead provides exact matches, typo correction, fuzzy matching and
        boosts subreddits to the top that the user is subscribed to.
      tags:
        - subreddits
  /api/subreddit_autocomplete_v2.json:
    get:
      operationId: GET_api_subreddit_autocomplete_v2
      security:
        - redditOAuth:
            - read
      description: ''
      tags:
        - subreddits
  '/r/{subreddit}/api/subreddit_stylesheet.json':
    post:
      operationId: POST_api_subreddit_stylesheet
      security:
        - redditOAuth:
            - modconfig
      description: |-
        Update a subreddit's stylesheet. 
        op should be save to update the contents of the stylesheet.
      tags:
        - subreddits
  /api/subscribe.json:
    post:
      operationId: POST_api_subscribe
      security:
        - redditOAuth:
            - subscribe
      description: >-
        Subscribe to or unsubscribe from a subreddit. 

        To subscribe, action should be sub. To unsubscribe, action should be
        unsub. The user must have access to the subreddit to be able to
        subscribe to it. 

        The skip_initial_defaults param can be set to True to prevent
        automatically subscribing the user to the current set of defaults when
        they take their first subscription action. Attempting to set it for an
        unsubscribe action will result in an error. 

        See also: /subreddits/mine/.
      tags:
        - subreddits
  '/r/{subreddit}/api/upload_sr_img.json':
    post:
      operationId: POST_api_upload_sr_img
      security:
        - redditOAuth:
            - modconfig
      description: >-
        Add or replace a subreddit image, custom header logo, custom mobile
        icon, or custom mobile banner. 
         
        If the upload_type value is img, an image for use in the subreddit
        stylesheet is uploaded with the name specified in name. 

        If the upload_type value is header then the image uploaded will be the
        subreddit's new logo and name will be ignored. 

        If the upload_type value is icon then the image uploaded will be the
        subreddit's new mobile icon and name will be ignored. 

        If the upload_type value is banner then the image uploaded will be the
        subreddit's new mobile banner and name will be ignored.  

        For backwards compatibility, if upload_type is not specified, the header
        field will be used instead: 
         
        If the header field has value 0, then upload_type is img. 

        If the header field has value 1, then upload_type is header.  

        The img_type field specifies whether to store the uploaded image as a
        PNG or JPEG. 

        Subreddits have a limited number of images that can be in use at any
        given time. If no image with the specified name already exists, one of
        the slots will be consumed. 

        If an image with the specified name already exists, it will be replaced.
        This does not affect the stylesheet immediately, but will take effect
        the next time the stylesheet is saved. 

        See also: /api/delete_sr_img, /api/delete_sr_header,
        /api/delete_sr_icon, and /api/delete_sr_banner.
      tags:
        - subreddits
  '/api/v1/{subreddit}/post_requirements.json':
    get:
      operationId: 'GET_api_v1_{subreddit}_post_requirements'
      security:
        - redditOAuth:
            - submit
      description: >-
        Fetch moderator-designated requirements to post to the subreddit. 

        Moderators may enable certain restrictions, such as minimum title
        length, when making a submission to their subreddit. 

        Clients may use the values returned by this endpoint to pre-validate
        fields before making a request to POST /api/submit. This may allow the
        client to provide a better user experience to the user, for example by
        creating a text field in their app that does not allow the user to enter
        more characters than the max title length. 

        A non-exhaustive list of possible requirements a moderator may enable: 
         
        body_blacklisted_strings: List of strings. Users may not submit posts
        that contain these words. 

        body_restriction_policy: String. One of "required", "notAllowed", or
        "none", meaning that a self-post body is required, not allowed, or
        optional, respectively. 

        domain_blacklist: List of strings. Users may not submit links to these
        domains 

        domain_whitelist: List of strings. Users submissions MUST be from one of
        these domains 

        is_flair_required: Boolean. If True, flair must be set at submission
        time. 

        title_blacklisted_strings: List of strings. Submission titles may NOT
        contain any of the listed strings. 

        title_required_strings: List of strings. Submission title MUST contain
        at least ONE of the listed strings. 

        title_text_max_length: Integer. Maximum length of the title field. 

        title_text_min_length: Integer. Minimum length of the title field.
      tags:
        - subreddits
  '/r/{subreddit}/about.json':
    get:
      operationId: 'GET_r_{subreddit}_about'
      security:
        - redditOAuth:
            - read
      description: |-
        Return information about the subreddit. 
        Data includes the subscriber count, description, and header image.
      tags:
        - subreddits
  '/r/{subreddit}/about/edit.json':
    get:
      operationId: 'GET_r_{subreddit}_about_edit'
      security:
        - redditOAuth:
            - modconfig
      description: >-
        Get the current settings of a subreddit. 

        In the API, this returns the current settings of the subreddit as used
        by /api/site_admin. On the HTML site, it will display a form for editing
        the subreddit.
      tags:
        - subreddits
  '/r/{subreddit}/about/rules.json':
    get:
      operationId: 'GET_r_{subreddit}_about_rules'
      security:
        - redditOAuth:
            - read
      description: Get the rules for the current subreddit
      tags:
        - subreddits
  '/r/{subreddit}/about/traffic.json':
    get:
      operationId: 'GET_r_{subreddit}_about_traffic'
      security:
        - redditOAuth:
            - modconfig
      description: ''
      tags:
        - subreddits
  '/r/{subreddit}/sidebar.json':
    get:
      operationId: GET_sidebar
      security:
        - redditOAuth:
            - read
      description: Get the sidebar for the current subreddit
      tags:
        - subreddits
  '/r/{subreddit}/sticky.json':
    get:
      operationId: GET_sticky
      security:
        - redditOAuth:
            - read
      description: >-
        Redirect to one of the posts stickied in the current subreddit 

        The "num" argument can be used to select a specific sticky, and will
        default to 1 (the top sticky) if not specified. Will 404 if there is not
        currently a sticky post in this subreddit.
      tags:
        - subreddits
  /subreddits/mine/subscriber.json:
    get:
      operationId: GET_subreddits_mine_subscriber
      security: &ref_52
        - redditOAuth:
            - mysubreddits
      description: >-
        Get subreddits the user has a relationship with. 

        The where parameter chooses which subreddits are returned as follows: 
         
        subscriber - subreddits the user is subscribed to 

        contributor - subreddits the user is an approved user in 

        moderator - subreddits the user is a moderator of 

        streams - subscribed to subreddits that contain hosted video links  

        See also: /api/subscribe, /api/friend, and
        /api/accept_moderator_invite. 

        This endpoint is a listing.
      tags: &ref_53
        - subreddits
  /subreddits/mine/contributor.json:
    get:
      operationId: GET_subreddits_mine_contributor
      security: *ref_52
      description: >-
        Get subreddits the user has a relationship with. 

        The where parameter chooses which subreddits are returned as follows: 
         
        subscriber - subreddits the user is subscribed to 

        contributor - subreddits the user is an approved user in 

        moderator - subreddits the user is a moderator of 

        streams - subscribed to subreddits that contain hosted video links  

        See also: /api/subscribe, /api/friend, and
        /api/accept_moderator_invite. 

        This endpoint is a listing.
      tags: *ref_53
  /subreddits/mine/moderator.json:
    get:
      operationId: GET_subreddits_mine_moderator
      security: *ref_52
      description: >-
        Get subreddits the user has a relationship with. 

        The where parameter chooses which subreddits are returned as follows: 
         
        subscriber - subreddits the user is subscribed to 

        contributor - subreddits the user is an approved user in 

        moderator - subreddits the user is a moderator of 

        streams - subscribed to subreddits that contain hosted video links  

        See also: /api/subscribe, /api/friend, and
        /api/accept_moderator_invite. 

        This endpoint is a listing.
      tags: *ref_53
  /subreddits/mine/streams.json:
    get:
      operationId: GET_subreddits_mine_streams
      security: *ref_52
      description: >-
        Get subreddits the user has a relationship with. 

        The where parameter chooses which subreddits are returned as follows: 
         
        subscriber - subreddits the user is subscribed to 

        contributor - subreddits the user is an approved user in 

        moderator - subreddits the user is a moderator of 

        streams - subscribed to subreddits that contain hosted video links  

        See also: /api/subscribe, /api/friend, and
        /api/accept_moderator_invite. 

        This endpoint is a listing.
      tags: *ref_53
  '/subreddits/search{read}.json':
    get:
      operationId: GET_subreddits_search
      security:
        - redditOAuth:
            - read
      description: |-
        Search subreddits by title and description. 
        This endpoint is a listing.
      tags:
        - subreddits
  /subreddits/popular.json:
    get:
      operationId: GET_subreddits_popular
      security: &ref_61
        - redditOAuth:
            - read
      description: >-
        Get all subreddits. 

        The where parameter chooses the order in which the subreddits are
        displayed. popular sorts on the activity of the subreddit and the
        position of the subreddits can shift around. new sorts the subreddits
        based on their creation date, newest first. 

        This endpoint is a listing.
      tags: &ref_62
        - subreddits
  /subreddits/new.json:
    get:
      operationId: GET_subreddits_new
      security: *ref_61
      description: >-
        Get all subreddits. 

        The where parameter chooses the order in which the subreddits are
        displayed. popular sorts on the activity of the subreddit and the
        position of the subreddits can shift around. new sorts the subreddits
        based on their creation date, newest first. 

        This endpoint is a listing.
      tags: *ref_62
  /subreddits/gold.json:
    get:
      operationId: GET_subreddits_gold
      security: *ref_61
      description: >-
        Get all subreddits. 

        The where parameter chooses the order in which the subreddits are
        displayed. popular sorts on the activity of the subreddit and the
        position of the subreddits can shift around. new sorts the subreddits
        based on their creation date, newest first. 

        This endpoint is a listing.
      tags: *ref_62
  /subreddits/default.json:
    get:
      operationId: GET_subreddits_default
      security: *ref_61
      description: >-
        Get all subreddits. 

        The where parameter chooses the order in which the subreddits are
        displayed. popular sorts on the activity of the subreddit and the
        position of the subreddits can shift around. new sorts the subreddits
        based on their creation date, newest first. 

        This endpoint is a listing.
      tags: *ref_62
  '/users/search{read}.json':
    get:
      operationId: GET_users_search
      security:
        - redditOAuth:
            - read
      description: |-
        Search user profiles by title and description. 
        This endpoint is a listing.
      tags:
        - subreddits
  /users/popular.json:
    get:
      operationId: GET_users_popular
      security: &ref_70
        - redditOAuth:
            - read
      description: >-
        Get all user subreddits. 

        The where parameter chooses the order in which the subreddits are
        displayed. popular sorts on the activity of the subreddit and the
        position of the subreddits can shift around. new sorts the user
        subreddits based on their creation date, newest first. 

        This endpoint is a listing.
      tags: &ref_71
        - subreddits
  /users/new.json:
    get:
      operationId: GET_users_new
      security: *ref_70
      description: >-
        Get all user subreddits. 

        The where parameter chooses the order in which the subreddits are
        displayed. popular sorts on the activity of the subreddit and the
        position of the subreddits can shift around. new sorts the user
        subreddits based on their creation date, newest first. 

        This endpoint is a listing.
      tags: *ref_71
  /api/block_user.json:
    post:
      operationId: POST_api_block_user
      security:
        - redditOAuth:
            - account
      description: For blocking a user.
      tags:
        - users
  '/r/{subreddit}/api/friend.json':
    post:
      operationId: POST_api_friend
      security:
        - redditOAuth:
            - any
      description: >-
        Create a relationship between a user and another user or subreddit 

        OAuth2 use requires appropriate scope based on the 'type' of the
        relationship: 
         
        moderator: Use "moderator_invite" 

        moderator_invite: modothers 

        contributor: modcontributors 

        banned: modcontributors 

        muted: modcontributors 

        wikibanned: modcontributors and modwiki 

        wikicontributor: modcontributors and modwiki 

        friend: Use /api/v1/me/friends/{username} 

        enemy: Use /api/block  

        Complement to POST_unfriend
      tags:
        - users
  /api/report_user.json:
    post:
      operationId: POST_api_report_user
      security:
        - redditOAuth:
            - report
      description: >-
        Report a user. Reporting a user brings it to the attention of a Reddit
        admin.
      tags:
        - users
  '/r/{subreddit}/api/setpermissions.json':
    post:
      operationId: POST_api_setpermissions
      security:
        - redditOAuth:
            - modothers
      description: ''
      tags:
        - users
  '/r/{subreddit}/api/unfriend.json':
    post:
      operationId: POST_api_unfriend
      security:
        - redditOAuth:
            - any
      description: >-
        Remove a relationship between a user and another user or subreddit 

        The user can either be passed in by name (nuser) or by fullname (iuser).
        If type is friend or enemy, 'container' MUST be the current user's
        fullname; for other types, the subreddit must be set via URL (e.g.,
        /r/funny/api/unfriend) 

        OAuth2 use requires appropriate scope based on the 'type' of the
        relationship: 
         
        moderator: modothers 

        moderator_invite: modothers 

        contributor: modcontributors 

        banned: modcontributors 

        muted: modcontributors 

        wikibanned: modcontributors and modwiki 

        wikicontributor: modcontributors and modwiki 

        friend: Use /api/v1/me/friends/{username} 

        enemy: privatemessages  

        Complement to POST_friend
      tags:
        - users
  /api/user_data_by_account_ids.json:
    get:
      operationId: GET_api_user_data_by_account_ids
      security:
        - redditOAuth:
            - privatemessages
      description: ''
      tags:
        - users
  /api/username_available.json:
    get:
      operationId: GET_api_username_available
      security:
        - redditOAuth:
            - any
      description: Check whether a username is available for registration.
      tags:
        - users
  '/api/v1/me/friends/{username}.json':
    delete:
      operationId: 'DELETE_api_v1_me_friends_{username}'
      security:
        - redditOAuth:
            - subscribe
      description: Stop being friends with a user.
      tags:
        - users
    get:
      operationId: 'GET_api_v1_me_friends_{username}'
      security:
        - redditOAuth:
            - mysubreddits
      description: 'Get information about a specific ''friend'', such as notes.'
      tags:
        - users
    put:
      operationId: 'PUT_api_v1_me_friends_{username}'
      security:
        - redditOAuth:
            - subscribe
      description: >-
        Create or update a "friend" relationship. 

        This operation is idempotent. It can be used to add a new friend, or
        update an existing friend (e.g., add/change the note on that friend)
      tags:
        - users
  '/api/v1/user/{username}/trophies.json':
    get:
      operationId: 'GET_api_v1_user_{username}_trophies'
      security:
        - redditOAuth:
            - read
      description: Return a list of trophies for the a given user.
      tags:
        - users
  '/user/{username}/about.json':
    get:
      operationId: 'GET_user_{username}_about'
      security:
        - redditOAuth:
            - read
      description: 'Return information about the user, including karma and gold status.'
      tags:
        - users
  '/user/{username}/overview.json':
    get:
      operationId: 'GET_user_{username}_overview'
      security: &ref_79
        - redditOAuth:
            - history
      description: This endpoint is a listing.
      tags: &ref_80
        - users
  '/user/{username}/submitted.json':
    get:
      operationId: 'GET_user_{username}_submitted'
      security: *ref_79
      description: This endpoint is a listing.
      tags: *ref_80
  '/user/{username}/comments.json':
    get:
      operationId: 'GET_user_{username}_comments'
      security: *ref_79
      description: This endpoint is a listing.
      tags: *ref_80
  '/user/{username}/upvoted.json':
    get:
      operationId: 'GET_user_{username}_upvoted'
      security: *ref_79
      description: This endpoint is a listing.
      tags: *ref_80
  '/user/{username}/downvoted.json':
    get:
      operationId: 'GET_user_{username}_downvoted'
      security: *ref_79
      description: This endpoint is a listing.
      tags: *ref_80
  '/user/{username}/hidden.json':
    get:
      operationId: 'GET_user_{username}_hidden'
      security: *ref_79
      description: This endpoint is a listing.
      tags: *ref_80
  '/user/{username}/saved.json':
    get:
      operationId: 'GET_user_{username}_saved'
      security: *ref_79
      description: This endpoint is a listing.
      tags: *ref_80
  '/user/{username}/gilded.json':
    get:
      operationId: 'GET_user_{username}_gilded'
      security: *ref_79
      description: This endpoint is a listing.
      tags: *ref_80
  '/r/{subreddit}/api/widget.json':
    post:
      operationId: POST_api_widget
      security:
        - redditOAuth:
            - structuredstyles
      description: >-
        Add and return a widget to the specified subreddit 

        Accepts a JSON payload representing the widget data to be saved. Valid
        payloads differ in shape based on the "kind" attribute passed on the
        root object, which must be a valid widget kind.
      tags:
        - widgets
  '/r/{subreddit}/api/widget/{widget_id}.json':
    delete:
      operationId: 'DELETE_api_widget_{widget_id}'
      security:
        - redditOAuth:
            - structuredstyles
      description: Delete a widget from the specified subreddit (if it exists)
      tags:
        - widgets
    put:
      operationId: 'PUT_api_widget_{widget_id}'
      security:
        - redditOAuth:
            - structuredstyles
      description: >-
        Update and return the data of a widget. 

        Accepts a JSON payload representing the widget data to be saved. Valid
        payloads differ in shape based on the "kind" attribute passed on the
        root object, which must be a valid widget kind.
      tags:
        - widgets
  '/r/{subreddit}/api/widget_image_upload_s3.json':
    post:
      operationId: POST_api_widget_image_upload_s3
      security:
        - redditOAuth:
            - structuredstyles
      description: >-
        Acquire and return an upload lease to s3 temp bucket. 

        The return value of this function is a json object containing
        credentials for uploading assets to S3 bucket, S3 url for upload request
        and the key to use for uploading. Using this lease the client will
        upload the emoji image to S3 temp bucket (included as part of the S3
        URL). 

        This lease is used by S3 to verify that the upload is authorized.
      tags:
        - widgets
  '/r/{subreddit}/api/widget_order/{section}.json':
    patch:
      operationId: 'PATCH_api_widget_order_{section}'
      security:
        - redditOAuth:
            - structuredstyles
      description: Update the order of widget_ids in the specified subreddit
      tags:
        - widgets
  '/r/{subreddit}/api/widgets.json':
    get:
      operationId: GET_api_widgets
      security:
        - redditOAuth:
            - structuredstyles
      description: Return all widgets for the given subreddit
      tags:
        - widgets
  '/r/{subreddit}/api/wiki/alloweditor/del.json':
    post:
      operationId: POST_api_wiki_alloweditor_del
      security: &ref_93
        - redditOAuth:
            - modwiki
      description: Allow/deny username to edit this wiki page
      tags: &ref_94
        - wiki
  '/r/{subreddit}/api/wiki/alloweditor/add.json':
    post:
      operationId: POST_api_wiki_alloweditor_add
      security: *ref_93
      description: Allow/deny username to edit this wiki page
      tags: *ref_94
  '/r/{subreddit}/api/wiki/edit.json':
    post:
      operationId: POST_api_wiki_edit
      security:
        - redditOAuth:
            - wikiedit
      description: Edit a wiki page
      tags:
        - wiki
  '/r/{subreddit}/api/wiki/hide.json':
    post:
      operationId: POST_api_wiki_hide
      security:
        - redditOAuth:
            - modwiki
      description: Toggle the public visibility of a wiki page revision
      tags:
        - wiki
  '/r/{subreddit}/api/wiki/revert.json':
    post:
      operationId: POST_api_wiki_revert
      security:
        - redditOAuth:
            - modwiki
      description: Revert a wiki page to revision
      tags:
        - wiki
  '/r/{subreddit}/wiki/discussions/{page}.json':
    get:
      operationId: 'GET_wiki_discussions_{page}'
      security:
        - redditOAuth:
            - wikiread
      description: |-
        Retrieve a list of discussions about this wiki page 
        This endpoint is a listing.
      tags:
        - wiki
  '/r/{subreddit}/wiki/pages.json':
    get:
      operationId: GET_wiki_pages
      security:
        - redditOAuth:
            - wikiread
      description: Retrieve a list of wiki pages in this subreddit
      tags:
        - wiki
  '/r/{subreddit}/wiki/revisions.json':
    get:
      operationId: GET_wiki_revisions
      security:
        - redditOAuth:
            - wikiread
      description: Retrieve a list of recently changed wiki pages in this subreddit
      tags:
        - wiki
  '/r/{subreddit}/wiki/revisions/{page}.json':
    get:
      operationId: 'GET_wiki_revisions_{page}'
      security:
        - redditOAuth:
            - wikiread
      description: |-
        Retrieve a list of revisions of this wiki page 
        This endpoint is a listing.
      tags:
        - wiki
  '/r/{subreddit}/wiki/settings/{page}.json':
    get:
      operationId: 'GET_wiki_settings_{page}'
      security:
        - redditOAuth:
            - modwiki
      description: Retrieve the current permission settings for page
      tags:
        - wiki
    post:
      operationId: 'POST_wiki_settings_{page}'
      security:
        - redditOAuth:
            - modwiki
      description: Update the permissions and visibility of wiki page
      tags:
        - wiki
  '/r/{subreddit}/wiki/{page}.json':
    get:
      operationId: 'GET_wiki_{page}'
      security:
        - redditOAuth:
            - wikiread
      description: >-
        Return the content of a wiki page 

        If v is given, show the wiki page as it was at that version If both v
        and v2 are given, show a diff of the two
      tags:
        - wiki